### ISSUE TITLE
Double Check Microsoft.UI.Xaml Replaces Windows.UI.Xaml

### ISSUE THREAD

**Issue by LanceMcCarthy** [Sergio0694/Brainf_ckSharp#76] opened 2020-06-10 22:08 UTC
When right-clicking on the Textbox, the application crashes. The following output is available in the Windows Event Viewer

Event Viewer
```
Faulting application name: Brainf_ckSharp.Uwp.exe, version: 1.0.0.0, time stamp: 0x5ee155af
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.815, time stamp: 0x9fa806f2
Exception code: 0xc000027b
Fault offset: 0x0000000000713530
Faulting process id: 0x61ec
Faulting application start time: 0x01d63f71d635f57a
Faulting application path: C:\Program Files\WindowsApps\77cee5e8-8481-4e69-92bc-31cfb2a6bc2b_1.610.1.0_x64__4tcmghg6akv1r\Brainf_ckSharp.Uwp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 22e98e81-c491-492c-9b5c-e0806edd6751
Faulting package full name: 77cee5e8-8481-4e69-92bc-31cfb2a6bc2b_1.610.1.0_x64__4tcmghg6akv1r
Faulting package-relative application ID: App
```

Sergio has shared a screenshot (from DevCenter?) that further implicates the issue is in Windows.UI.Xaml in the crash

![image](https://user-images.githubusercontent.com/3520532/84323650-2f20e700-ab45-11ea-98b1-9d8b94900963.png)

I'm surprised that Windows.UI.Xaml is being used instead of Microsoft.UI.Xaml, but I'm not well versed in how the WinUI sets the types under the covers. This could well be the expected output for a crash on a WinUI ContentPresenter.

**Comment by Sergio0694** [comment] 2023-01-06 19:24
Closing this as I think the issue is fixed now (can right click and it works just fine). Thank you again for the help! 😄

**Closed by Sergio0694** 2023-01-06 19:24 UTC
